apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mohd1995/AWS-CICD'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-sre
  syncPolicy:
    automated:
      selfHeal: true
      prune: true



dOOBCsPS4vc9kb8C