apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    app.kubernetes.io/instance: my-ingress-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: DATABASE_PATH
              value: "{{ .Values.backend.env.DATABASE_PATH }}"
          volumeMounts:
            - mountPath: "{{ .Values.backend.env.DATABASE_PATH }}"
              name: sqlite-storage
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: {{ .Values.backend.pvcName }}
