apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    app.kubernetes.io/instance: my-ingress-app
  name: frontend
  namespace: my-sre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - env:
            - name: DATABASE_PATH
              value: /data/
          image: 'mohd1995/frontend-sre:latest'
          name: frontend
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /data/portfolio_contacts.db
              name: sqlite-storage
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: my-pvc
