apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    app.kubernetes.io/instance: my-ingress-app
  name: frontend
  namespace: my-sre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - env:
            - name: API_BASE_URL
              value: 'http://moesportfolio.com'
          image: mohd1995/frontend-sre:latest'
          name: frontend
          ports:
          - containerPort: 8080
