name: Flask Web App CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  clean-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        uses: actions/checkout@v4
        with:
          clean: true

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4
      - name: Validate HTML & CSS (Optional)
        run: echo "Static HTML/CSS site - no tests to run"

  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'
      - name: Install dependencies and test
      
        run: |
          pip install --upgrade pip 
          pip install -r requirements.txt
          flake8
          #pytest

        env:
          FLASK_ENV: testing
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: backend
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=mohd-1995_AWS-CICD
            -Dsonar.host.url=${{ secrets.SONAR_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=.
            -Dsonar.language=py
            -Dsonar.verbose=true


          
        
